export const MENU_DESCRIPTION_BY_NAME: Record<string, string> = {
  "Sữa Dâu Sấy Trăng Hoa": "Vị dâu tươi, sữa dẻo, giòn thơm mát, dễ gây nghiện.",
  "Sữa Chua Dẻo Cốm Xoài Trân Châu": "Sữa chua dẻo, cốm thơm, xoài tươi, trân châu thơm ngon.",
  "Dưa Hấu Đá Sayy - Sinh Tố Dưa Hấu Siêu Hot": "Dưa hấu tươi, đá xay, siêu mát lạnh, thức uống mùa hè sảng khoái.",
  "Nước Dừa Thạch Nổ Đậu Đỏ May Mắn": "Nước dừa thơm mát, thạch nổ đậu đỏ vui miệng, uống cực cuốn.",
  "Nước Dừa Hạt Chia": "Nước dừa thanh mát, hạt chia bổ dưỡng, tặng thạch dừa mát lạnh.",
  "Nước Dừa Tươi": "Nước dừa tươi ngọt mát, thêm thạch dừa dai mềm, thơm ngon tự nhiên.",
  "Nước Dừa Nước Mát Long Vương": "Nước dừa thơm ngọt dịu, trân châu dẻo ngon.",
  "Nước Dừa Hạt Sen Thanh Mát Giải Nhiệt": "Nước dừa tươi, hạt sen mềm mại, giải nhiệt dễ chịu.",
  "Nước Dừa Kem Matcha Siêu Phê Nhà Phee": "Matcha thơm mịn, nước dừa ngọt thanh, vị phê sảng khoái.",
  "Sen Dừa Quế Hoa Thơm Dịu Nhẹ Nhàng": "Hương quế nhẹ nhàng, dừa ngọt mát, sen ngọt bùi.",
  "Choco Bạc Hà Đá Say Mát Lạnh Sảng Khoái": "Bạc hà tươi mát, socola ngọt, đá lạnh sảng khoái, giải nhiệt ngày hè.",
  "Trà Măng Cầu Tươi": "Trà mãng cầu tươi thơm ngon, ngọt mát, bổ dưỡng, giải nhiệt ngày hè.",
  "Matcha Latte Quế Hoa Topping Linh Tinh": "Matcha đậm đà, quế hoa thơm, linh tinh topping hấp dẫn.",
  "Trà Nhài Cam Mây Trắng Bồng Bềnh": "Trà nhài dịu nhẹ, cam tươi mát, mây trắng bồng bềnh thơm lừng.",
  "Trà Mãng Cầu Quế Hoa Hot Trend": "Trà mãng cầu thơm mùi quế hoa, một màn đêm hương vị độc đáo.",
  "Bạc Xỉu Up Xỉu Down": "Khách uống nóng ghi chú giúp quán sửa đặc, sữa tươi, đá lạnh tạo nên ly bạc xỉu thơm ngon, mát lạnh.",
  "YaKuLựu Đỏ Trân Châu": "Yakult ngọt thanh hòa quyện cùng lựu đỏ tốt cho tiêu hóa đẹp da.",
  "Sữa Chua Xoài Dẻo Trân Châu": "Sữa chua mềm mại, xoài ngọt, trân châu dai giòn, thơm mát.",
  "Hoa Quả Dầm Sữa Chua Dẻo": "Sữa chua dẻo kết hợp trái cây tươi, ngọt mát, thơm ngon.",
  "Nước Dừa Quế Hoa Hot Trend Siêu Cuốn": "Nước dừa thơm, quế quyện cùng hoa hồng, siêu mát mẻ, cuốn hút từng ly.",
  "Bơ Già Dừa Nướng Siêu Ngon": "Bơ già dừa ngon, béo ngậy, thơm mùi dừa tự nhiên.",
  "Nước Ép Cam": "Nước cam tươi, ngọt mát, bổ sung vitamin tự nhiên.",
  "Matcha Latte Siêu Cuốnnnn": "Matcha latte trà xanh thơm lừng, siêu cuốn kết hợp cùng sữa tươi.",
  "Trà Sữa Cốm Non": "Trà sữa thơm mùi cốm non, topping trân châu giòn tan, ngọt ngào khó cưỡng.",
  "Nước Ép Roi Đỏ": "Nước ép roi đỏ tươi mát, ngọt dịu, bổ sung vitamin tự nhiên.",
  "Trà Mận Nhiệt Đới": "Mứt mận nguyên miếng kết hợp cùng trà nhài thơm ngon đậm vị, uống giải khát cực đã.",
  "Kem Dừa Cốm Non Siêu Ngon": "Kem dừa mềm mại, cốm non giòn, béo ngậy, thơm ngon mát lành.",
  "Hoa Quả Dầm Kem Dừa Trân Châu": "Hoa quả tươi theo mùa, kem dừa béo ngậy, trân châu mềm mịn thơm ngon.",
  "Kem Bơ Dừa Đà Lạt": "Kem dừa cồn cào, kết hợp cùng bơ Đà Lạt và dừa khô, cực thơm và ngon béo.",
  "Kem Bơ Sầu Riêng": "Sinh tố bơ tươi mềm mịn kết hợp cùng kem sầu và dừa khô thơm lừng, ăn mát tan siêu cuốn.",
  "Nước Ép Dưa Hấu": "Nước ép dưa hấu tươi, thêm topping nha đam mát lạnh, giải nhiệt ngày hè.",
  "Nước Ép Cóc Mix Ổi": "Nước ép cóc mix ổi tươi mát, ngọt ngào và thơm phức.",
  "Nước Ép Ổi - Chanh Leo": "Nước ép ổi chanh leo thơm mát, tươi ngon, bổ dưỡng.",
  "Nước Ép Cóc - Dứa": "Cóc dứa tươi mới ngày ép bằng máy ép chậm, rất tươi ngon và giữ nguyên dưỡng chất.",
  "Nước Ép Cần Tây - Táo": "Thức uống healthy giúp detox cơ thể, giữ dáng và đẹp da.",
  "Nước Ép Cần Tây - Dứa - Ổi": "Thức uống healthy giúp detox cơ thể, giữ dáng và đẹp da.",
  "Nước Ép Cần Tây - Táo - Cà Rốt": "Thức uống healthy giúp detox cơ thể, giữ dáng và đẹp da.",
  "Nước Ép Cần Tây - Cam - Dứa": "Thức uống healthy giúp detox cơ thể, giữ dáng và đẹp da.",
  "Nước Ép Cam Mix Cà Rốt": "Nước ép cam kết hợp cùng cà rốt tươi theo mùa, tươi ngon và nguyên chất.",
  "Nước Ép Cam Mix Táo": "Nước ép cam tươi kết hợp cùng táo theo mùa tạo rất thơm ngon và nhiều dưỡng chất.",
  "Nước Ép Dứa Mix Táo": "Dứa và táo tươi ngon mỗi ngày, ép tươi đầu dùng tối đa tươi ngon đầy đủ dưỡng chất.",
  "Nước Ép Chanh Leo": "Chanh leo theo mùa tươi ngon mỗi ngày dùng tối đa ép tươi bằng máy ép chậm, rất tươi ngon và giữ nguyên dưỡng chất.",
  "Nước Ép Táo Mix Ổi": "Táo ổi theo mùa tươi ngon mỗi ngày dùng tối đa ép tươi đồ bằng máy ép chậm, rất tươi ngon và giữ nguyên dưỡng chất.",
  "Nước Ép Cóc Bao Tử": "Cóc bao tử tươi ngon mỗi ngày dùng tối đa ép tươi đồ bằng máy ép chậm, rất tươi ngon và giữ nguyên dưỡng chất.",
  "Nước Ép Cà Rốt": "Cà rốt theo mùa tươi ngon mỗi ngày dùng tối đa ép tươi đồ bằng máy ép chậm, rất tươi ngon và giữ nguyên dưỡng chất.",
  "Nước Ép Táo": "Táo theo mùa tươi ngon mỗi ngày dùng tối đa ép tươi đồ bằng máy ép chậm, rất tươi ngon và giữ nguyên dưỡng chất.",
  "Nước Ép Ổi": "Ổi theo mùa tươi ngon mỗi ngày dùng tối đa ép tươi đồ bằng máy ép chậm, rất tươi ngon và giữ nguyên dưỡng chất.",
  "Nước Ép Dứa": "Dứa tươi mỗi ngày ép tối đa dùng tối đa tươi ngon nguyên chất.",
  "Nước Ép Cam - Dứa": "Cam và dứa tươi mỗi ngày dùng tối đa ép đồ bằng máy ép chậm, rất tươi và giữ nguyên 100% dưỡng chất.",
  "Nước Ép Cần Tây - Dứa": "Nước ép detox, thanh lọc cơ thể, giúp đẹp da giữ dáng.",
  "Nước Ép Lựu": "Nước ép lựu tươi, giàu vitamin, giúp đào lại nhan.",
  "Sinh Tố Bơ Kem Chesse Món Mới Siêu Ngon": "Sinh tố bơ thơm ngon kết hợp kem chesse béo ngậy.",
  "Sinh Tố Bơ": "Bơ tươi mỗi ngày kết hợp cùng sữa vinamilk cho ra sinh tố sánh mịn, không dùng đường.",
  "Sinh Tố Xoài - Chanh Leo": "Xoài chanh leo tươi ngon kết hợp cùng sữa đặc và sữa tươi nguyên chất, không dùng đường.",
  "Sinh Tố Bơ Dừa": "Bơ tươi mỗi ngày kết hợp với nước cốt dừa, sữa tươi và sữa đặc vinamilk cho ra sinh tố sánh mịn, không dùng đường.",
  "Sinh Tố Bơ Xoài": "Xoài và bơ tươi mỗi ngày kết hợp cùng sữa vinamilk cho ra sinh tố sánh mịn, không sử dụng đường.",
  "Sinh Tố Mãng Cầu": "Mãng cầu tươi mỗi ngày kết hợp cùng sữa tươi và sữa đặc vinamilk cho ra món sinh tố ngon sánh mịn, không dùng đường.",
  "Sữa Chua Dẻo Cốm Non": "Sữa chua dẻo mát lạnh, kết hợp vị ngọt cốm non, topping dừa khô ngọt mịn.",
  "Sinh Tố Xoài Dừa": "Xoài tươi mỗi ngày kết hợp với nước cốt dừa, sữa tươi và sữa đặc vinamilk cho ra sinh tố sánh mịn, không đường.",
  "Sinh Tố Xoài Mãng Cầu": "Xoài tươi mỗi ngày kết hợp với mãng cầu, sữa tươi và sữa đặc vinamilk cho ra sinh tố sánh mịn, không dùng đường.",
  "Sinh Tố Xoài": "Xoài tươi mỗi ngày kết hợp cùng sữa vinamilk cho ra sinh tố sánh mịn, không sử dụng đường.",
  "Chanh Tuyết AvoMoRi - Sinh Tố Chanh Tuyết": "Chanh tuyết kết hợp cùng sữa và kem sữa cho ra món sinh tố chanh tươi mát giải nhiệt.",
};